<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use App\Models\PencatatanAwal;

class PencatatanKunjunganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (!Schema::hasTable('pencatatan_kunjungans')) {
            return;
        }

        // Pastikan ada data di tabel pencatatan_awal terlebih dahulu
        $pencatatanAwalIds = PencatatanAwal::pluck('id')->toArray();

        if (empty($pencatatanAwalIds)) {
            return;
        }

        DB::table('pencatatan_kunjungans')->insert([
            [
                'id_pencatatan_awal' => 1,
                'waktu_pencatatan' => now()->subDays(10),
                'berat_badan' => 3.2,
                'panjang_badan' => 50.5,
                'tinggi_badan' => 51.0,
                'lingkar_lengan' => 10.5,
                'lingkar_kepala' => 34.0,
                'lingkar_perut' => 30.5,
                'mt_bumil_kek' => null,
                'asi_eksklusif' => 1,
                'mp_asi' => 2,
                'mt_pangan_pemulihan' => 1,
                'catatan_kesehatan' => 'Sehat, pertumbuhan normal',
                'tes_mata_kanan' => 1,
                'tes_mata_kiri' => 1,
                'tes_telinga_kanan' => 1,
                'tes_telinga_kiri' => 1,
                'tekanan_darah_sistolik' => null,
                'tekanan_darah_diastolik' => null,
                'gula_darah' => null,
                'kolestrol' => null,
                'keluhan' => null,
                'edukasi' => 'Pentingnya imunisasi',
            ],
            [
                'id_pencatatan_awal' => 2,
                'waktu_pencatatan' => now()->subDays(20),
                'berat_badan' => 2.9,
                'panjang_badan' => 48.0,
                'tinggi_badan' => 49.0,
                'lingkar_lengan' => 9.8,
                'lingkar_kepala' => 33.5,
                'lingkar_perut' => 29.8,
                'mt_bumil_kek' => null,
                'asi_eksklusif' => 2,
                'mp_asi' => 1,
                'mt_pangan_pemulihan' => 2,
                'catatan_kesehatan' => 'Sedikit kurang berat badan',
                'tes_mata_kanan' => 1,
                'tes_mata_kiri' => 1,
                'tes_telinga_kanan' => 1,
                'tes_telinga_kiri' => 1,
                'tekanan_darah_sistolik' => 10,
                'tekanan_darah_diastolik' => 40,
                'gula_darah' => null,
                'kolestrol' => null,
                'keluhan' => 'Sering rewel',
                'edukasi' => 'Meningkatkan asupan gizi',
            ],
            [
                'id_pencatatan_awal' => 3,
                'waktu_pencatatan' => now()->subDays(30),
                'berat_badan' => 3.5,
                'panjang_badan' => 52.0,
                'tinggi_badan' => 52.5,
                'lingkar_lengan' => 11.0,
                'lingkar_kepala' => 34.5,
                'lingkar_perut' => 31.0,
                'mt_bumil_kek' => null,
                'asi_eksklusif' => 1,
                'mp_asi' => 1,
                'mt_pangan_pemulihan' => 1,
                'catatan_kesehatan' => 'Pertumbuhan baik',
                'tes_mata_kanan' => 1,
                'tes_mata_kiri' => 1,
                'tes_telinga_kanan' => 1,
                'tes_telinga_kiri' => 1,
                'tekanan_darah_sistolik' => null,
                'tekanan_darah_diastolik' => null,
                'gula_darah' => null,
                'kolestrol' => null,
                'keluhan' => null,
                'edukasi' => 'Lanjutkan pemberian ASI eksklusif',
            ],
            [
                'id_pencatatan_awal' => 4,
                'waktu_pencatatan' => now()->subDays(40),
                'berat_badan' => 3.1,
                'panjang_badan' => 49.5,
                'tinggi_badan' => 50.0,
                'lingkar_lengan' => 10.2,
                'lingkar_kepala' => 34.2,
                'lingkar_perut' => 30.2,
                'mt_bumil_kek' => null,
                'asi_eksklusif' => 2,
                'mp_asi' => 2,
                'mt_pangan_pemulihan' => 2,
                'catatan_kesehatan' => 'Dalam pemantauan dokter',
                'tes_mata_kanan' => 1,
                'tes_mata_kiri' => 1,
                'tes_telinga_kanan' => 1,
                'tes_telinga_kiri' => 1,
                'tekanan_darah_sistolik' => 20,
                'tekanan_darah_diastolik' => 30,
                'gula_darah' => null,
                'kolestrol' => null,
                'keluhan' => 'Pernapasan berbunyi',
                'edukasi' => 'Konsultasi lebih lanjut ke dokter',
            ],
            [
                'id_pencatatan_awal' => 5,
                'waktu_pencatatan' => now()->subDays(50),
                'berat_badan' => 4.2,
                'panjang_badan' => 52.0,
                'tinggi_badan' => 53.5,
                'lingkar_lengan' => 11.0,
                'lingkar_kepala' => 35.5,
                'lingkar_perut' => 31.8,
                'mt_bumil_kek' => 1,
                'asi_eksklusif' => 1,
                'mp_asi' => 2,
                'mt_pangan_pemulihan' => 1,
                'catatan_kesehatan' => 'Tidak ada keluhan signifikan',
                'tes_mata_kanan' => 2,
                'tes_mata_kiri' => 2,
                'tes_telinga_kanan' => 2,
                'tes_telinga_kiri' => 2,
                'tekanan_darah_sistolik' => 70,
                'tekanan_darah_diastolik' => 60,
                'gula_darah' => 85,
                'kolestrol' => 170,
                'keluhan' => 'Batuk ringan',
                'edukasi' => 'Jaga pola makan dan cukup istirahat',
            ],
            [
                'id_pencatatan_awal' => 6,
                'waktu_pencatatan' => now()->subDays(50),
                'berat_badan' => 4.3,
                'panjang_badan' => 52.5,
                'tinggi_badan' => 54.0,
                'lingkar_lengan' => 11.2,
                'lingkar_kepala' => 35.8,
                'lingkar_perut' => 32.0,
                'mt_bumil_kek' => 1,
                'asi_eksklusif' => 1,
                'mp_asi' => 2,
                'mt_pangan_pemulihan' => 1,
                'catatan_kesehatan' => 'Kondisi kesehatan stabil',
                'tes_mata_kanan' => 2,
                'tes_mata_kiri' => 2,
                'tes_telinga_kanan' => 2,
                'tes_telinga_kiri' => 2,
                'tekanan_darah_sistolik' => 72,
                'tekanan_darah_diastolik' => 62,
                'gula_darah' => 88,
                'kolestrol' => 165,
                'keluhan' => 'Tidak ada keluhan',
                'edukasi' => 'Tetap jaga pola makan dan perhatikan asupan gizi',

            ],
            [
                'id_pencatatan_awal' => 7,
                'waktu_pencatatan' => now()->subDays(50),
                'berat_badan' => 4.1,
                'panjang_badan' => 51.8,
                'tinggi_badan' => 53.2,
                'lingkar_lengan' => 10.9,
                'lingkar_kepala' => 35.3,
                'lingkar_perut' => 31.6,
                'mt_bumil_kek' => 1,
                'asi_eksklusif' => 1,
                'mp_asi' => 1,
                'mt_pangan_pemulihan' => 1,
                'catatan_kesehatan' => 'Tidak ditemukan masalah kesehatan',
                'tes_mata_kanan' => 2,
                'tes_mata_kiri' => 2,
                'tes_telinga_kanan' => 2,
                'tes_telinga_kiri' => 2,
                'tekanan_darah_sistolik' => 69,
                'tekanan_darah_diastolik' => 58,
                'gula_darah' => 87,
                'kolestrol' => 175,
                'keluhan' => 'Sedikit rewel saat malam',
                'edukasi' => 'Pastikan bayi cukup tidur dan mendapatkan nutrisi yang cukup',
            ],
            [
                'id_pencatatan_awal' => 8,
                'waktu_pencatatan' => now()->subDays(50),
                'berat_badan' => 4.4,
                'panjang_badan' => 53.0,
                'tinggi_badan' => 54.5,
                'lingkar_lengan' => 11.5,
                'lingkar_kepala' => 36.0,
                'lingkar_perut' => 32.2,
                'mt_bumil_kek' => 1,
                'asi_eksklusif' => 1,
                'mp_asi' => 2,
                'mt_pangan_pemulihan' => 1,
                'catatan_kesehatan' => 'Perkembangan baik, tidak ada gangguan signifikan',
                'tes_mata_kanan' => 2,
                'tes_mata_kiri' => 2,
                'tes_telinga_kanan' => 2,
                'tes_telinga_kiri' => 2,
                'tekanan_darah_sistolik' => 71,
                'tekanan_darah_diastolik' => 61,
                'gula_darah' => 86,
                'kolestrol' => 172,
                'keluhan' => 'Sedikit pilek',
                'edukasi' => 'Jaga kebersihan lingkungan dan hindari paparan udara dingin',
            ],
            [
                'id_pencatatan_awal' => 10,
                'waktu_pencatatan' => now()->subDays(50),
                'berat_badan' => 4.0,
                'panjang_badan' => 51.5,
                'tinggi_badan' => 52.8,
                'lingkar_lengan' => 10.8,
                'lingkar_kepala' => 35.0,
                'lingkar_perut' => 31.4,
                'mt_bumil_kek' => 1,
                'asi_eksklusif' => 1,
                'mp_asi' => 1,
                'mt_pangan_pemulihan' => 1,
                'catatan_kesehatan' => 'Perkembangan normal, tidak ada masalah',
                'tes_mata_kanan' => 2,
                'tes_mata_kiri' => 2,
                'tes_telinga_kanan' => 2,
                'tes_telinga_kiri' => 2,
                'tekanan_darah_sistolik' => 68,
                'tekanan_darah_diastolik' => 57,
                'gula_darah' => 89,
                'kolestrol' => 169,
                'keluhan' => 'Sering menangis saat malam',
                'edukasi' => 'Coba rutinitas tidur yang konsisten dan cek pola makan bayi',
            ],
            [
                'id_pencatatan_awal' => 10,
                'waktu_pencatatan' => now()->subDays(50),
                'berat_badan' => 4.5,
                'panjang_badan' => 53.3,
                'tinggi_badan' => 54.8,
                'lingkar_lengan' => 11.3,
                'lingkar_kepala' => 36.2,
                'lingkar_perut' => 32.4,
                'mt_bumil_kek' => 1,
                'asi_eksklusif' => 1,
                'mp_asi' => 2,
                'mt_pangan_pemulihan' => 1,
                'catatan_kesehatan' => 'Sehat, tidak ada gejala yang mengkhawatirkan',
                'tes_mata_kanan' => 2,
                'tes_mata_kiri' => 2,
                'tes_telinga_kanan' => 2,
                'tes_telinga_kiri' => 2,
                'tekanan_darah_sistolik' => 10,
                'tekanan_darah_diastolik' => 10,
                'gula_darah' => 84,
                'kolestrol' => 168,
                'keluhan' => 'Tidak ada keluhan',
                'edukasi' => 'Pertahankan pola makan dan pastikan bayi cukup aktif',
            ],
        ]);
    }
}
