<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PendaftaranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // Ibu Hamil (jenis_sasaran = 1)
            [
                'nik' => '3174010101010001',
                'nama' => 'Siti Aminah',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1995-03-12',
                'pendidikan' => 4,
                'pekerjaan' => 3,
                'alamat' => 'Jl. Melati No. 1',
                'no_hp' => '081234567891',
                'no_jkn' => 'JKN12345678',
                'jenis_sasaran' => 1,
                'data_posyandu_id' => 1,
            ],
            [
                'nik' => '3174010101010002',
                'nama' => 'Rina Kartika',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1993-05-20',
                'pendidikan' => 3,
                'pekerjaan' => 2,
                'alamat' => 'Jl. Kenanga No. 2',
                'no_hp' => '081234567892',
                'no_jkn' => 'JKN22345678',
                'jenis_sasaran' => 1,
                'data_posyandu_id' => 1,
            ],
            [
                'nik' => '3174010101010003',
                'nama' => 'Lestari Dewi',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1996-07-18',
                'pendidikan' => 2,
                'pekerjaan' => 4,
                'alamat' => 'Jl. Mawar No. 3',
                'no_hp' => '081234567893',
                'no_jkn' => null,
                'jenis_sasaran' => 1,
                'data_posyandu_id' => 1,
            ],
            [
                'nik' => '3174010101010004',
                'nama' => 'Fitri Handayani',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '1992-08-11',
                'pendidikan' => 5,
                'pekerjaan' => 1,
                'alamat' => 'Jl. Flamboyan No. 4',
                'no_hp' => '081234567894',
                'no_jkn' => 'JKN32345678',
                'jenis_sasaran' => 1,
                'data_posyandu_id' => 4,
            ],
            [
                'nik' => '3174010101010005',
                'nama' => 'Ani Pratiwi',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '1994-01-25',
                'pendidikan' => 6,
                'pekerjaan' => 2,
                'alamat' => 'Jl. Dahlia No. 5',
                'no_hp' => '081234567895',
                'no_jkn' => null,
                'jenis_sasaran' => 1,
                'data_posyandu_id' => 5,
            ],

            // Balita (jenis_sasaran = 2)
            [
                'nik' => '3174010202020001',
                'nama' => 'Andi Pratama',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2020-02-15',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Anggrek No. 1',
                'no_hp' => '081234567896',
                'no_jkn' => 'JKN42345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 1,
            ],
            [
                'nik' => '3174010202020002',
                'nama' => 'Budi Santoso',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2019-08-22',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Teratai No. 2',
                'no_hp' => '081234567897',
                'no_jkn' => null,
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 2,
            ],
            [
                'nik' => '3174010202020003',
                'nama' => 'Citra Larasati',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2021-04-10',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Melur No. 3',
                'no_hp' => '081234567898',
                'no_jkn' => 'JKN52345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 3,
            ],
            [
                'nik' => '3174010202020004',
                'nama' => 'Doni Saputra',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2020-10-05',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Sakura No. 4',
                'no_hp' => '081234567899',
                'no_jkn' => null,
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 4,
            ],
            [
                'nik' => '3174010202020005',
                'nama' => 'Eka Wulandari',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '2018-12-01',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Nusa Indah No. 5',
                'no_hp' => '081234567800',
                'no_jkn' => 'JKN62345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 5,
            ],
            [
                'nik' => '3174010202020006',
                'nama' => 'Fauzan Rizki',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2021-11-20',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Merpati No. 6',
                'no_hp' => '081234567801',
                'no_jkn' => 'JKN72345679',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 1,
            ],
            [
                'nik' => '3174010202020007',
                'nama' => 'Galih Permana',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2020-06-15',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Anggrek No. 7',
                'no_hp' => '081234567802',
                'no_jkn' => 'JKN82345679',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 2,
            ],
            [
                'nik' => '3174010202020008',
                'nama' => 'Raisa Nabila',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2019-01-30',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Merdeka No. 8',
                'no_hp' => '081234567803',
                'no_jkn' => 'JKN92345679',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 2,
            ],
            [
                'nik' => '3174010202020009',
                'nama' => 'Dewi Arimbi',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2020-05-17',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Pahlawan No. 9',
                'no_hp' => '081234567804',
                'no_jkn' => 'JKN10345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 2,
            ],
            [
                'nik' => '3174010202020010',
                'nama' => 'Fika Wahyuni',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '2019-03-22',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Bunga No. 10',
                'no_hp' => '081234567805',
                'no_jkn' => 'JKN11345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 2,
            ],
            [
                'nik' => '3174010202020006',
                'nama' => 'Farhan Ananda',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2021-06-25',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Merpati No. 6',
                'no_hp' => '081234567810',
                'no_jkn' => 'JKN72345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 1,
            ],
            [
                'nik' => '3174010202020007',
                'nama' => 'Hana Salsabila',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2021-02-17',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Kenanga No. 7',
                'no_hp' => '081234567811',
                'no_jkn' => 'JKN82345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 2,
            ],
            [
                'nik' => '3174010202020008',
                'nama' => 'Rama Maulana',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2022-03-11',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Melati No. 8',
                'no_hp' => '081234567812',
                'no_jkn' => 'JKN92345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 3,
            ],
            [
                'nik' => '3174010202020009',
                'nama' => 'Nina Wulandari',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2020-09-15',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Dahlia No. 9',
                'no_hp' => '081234567813',
                'no_jkn' => 'JKN02345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 4,
            ],
            [
                'nik' => '3174010202020010',
                'nama' => 'Mikhaela Putri',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '2022-01-30',
                'pendidikan' => 1,
                'pekerjaan' => 6,
                'alamat' => 'Jl. Nusa Indah No. 10',
                'no_hp' => '081234567814',
                'no_jkn' => 'JKN12345678',
                'jenis_sasaran' => 2,
                'data_posyandu_id' => 5,
            ],

            // Lansia (jenis_sasaran = 3)
            [
                'nik' => '3174010303030001',
                'nama' => 'Suharto',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1950-01-12',
                'pendidikan' => 3,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Cemara No. 1',
                'no_hp' => '081234567801',
                'no_jkn' => 'JKN72345678',
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 1,
            ],
            [
                'nik' => '3174010303030002',
                'nama' => 'Mariam',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1952-03-25',
                'pendidikan' => 2,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Cemara No. 2',
                'no_hp' => '081234567802',
                'no_jkn' => 'JKN82345678',
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 2,
            ],
            [
                'nik' => '3174010303030003',
                'nama' => 'Hendro Wijaya',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1955-09-10',
                'pendidikan' => 4,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Cemara No. 3',
                'no_hp' => '081234567803',
                'no_jkn' => null,
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 3,
            ],
            [
                'nik' => '3174010303030004',
                'nama' => 'Yanti',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '1958-06-30',
                'pendidikan' => 3,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Cemara No. 4',
                'no_hp' => '081234567804',
                'no_jkn' => 'JKN92345678',
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 2,
            ],
            [
                'nik' => '3174010303030005',
                'nama' => 'Rukmini',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '1951-11-20',
                'pendidikan' => 5,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Cemara No. 5',
                'no_hp' => '081234567805',
                'no_jkn' => null,
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 5,
            ],
            [
                'nik' => '3174010303030006',
                'nama' => 'Marto Suwito',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1948-02-14',
                'pendidikan' => 3,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Kenanga No. 6',
                'no_hp' => '081234567806',
                'no_jkn' => 'JKN10345679',
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 1,
            ],
            [
                'nik' => '3174010303030007',
                'nama' => 'Tati Marwati',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1956-12-05',
                'pendidikan' => 4,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Merpati No. 7',
                'no_hp' => '081234567807',
                'no_jkn' => 'JKN11345679',
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 2,
            ],
            [
                'nik' => '3174010303030008',
                'nama' => 'Warman Hadi',
                'jenis_kelamin' => 1,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '1953-11-22',
                'pendidikan' => 2,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Cempaka No. 8',
                'no_hp' => '081234567808',
                'no_jkn' => 'JKN12345679',
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 3,
            ],
            [
                'nik' => '3174010303030009',
                'nama' => 'Siti Badriah',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 2,
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '1957-08-15',
                'pendidikan' => 4,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Teratai No. 9',
                'no_hp' => '081234567809',
                'no_jkn' => 'JKN13345679',
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 4,
            ],
            [
                'nik' => '3174010303030010',
                'nama' => 'Sukmawati',
                'jenis_kelamin' => 2,
                'status_perkawinan' => 1,
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '1960-07-19',
                'pendidikan' => 3,
                'pekerjaan' => 7,
                'alamat' => 'Jl. Manggis No. 10',
                'no_hp' => '081234567810',
                'no_jkn' => 'JKN14345679',
                'jenis_sasaran' => 3,
                'data_posyandu_id' => 2,
            ],
        ];

        foreach ($data as $item) {
            DB::table('pendaftarans')->insert(array_merge($item, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
